# SERVER CONFIGURATION
server:
  port: 8092
  servlet:
    context-path: "/${spring.application.name}"

# SPRING CONFIGURATION
spring:
  application:
    name: friendlist
  # SPRING JPA CONFIGURATION
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/friendlist_management
    username: postgres
    password: root
  jpa:
    open-in-view: false
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
  jackson:
    default-property-inclusion: NON_NULL
  mail:
    host: smtp.gmail.com
    port: 587
    username: test.friendlist.123@gmail.com
    password: ejbzjgqnupdqfuxb
    properties:
      mail:
         smtp:
            auth: true
            starttls:
              enable: true

# LOGGING CONFIGURATION
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE





